---
- name: Check if Elasticsearch is installed
  stat:
    path: /usr/share/elasticsearch/bin/elasticsearch
  register: stat_result

- name: Set fact from previous task
  set_fact:
    es_new_install: not stat_result.stat.exists

- name: Current Elasticsearch version (shell command)
  shell:  "/usr/share/elasticsearch/bin/elasticsearch --version"
  register: es_versions_shell
  ignore_errors: true
  when: not es_new_install

- name: Current Elasticsearch version (set fact)
  set_fact:
    current_es_version: "{{ es_version_shell.stdout|split(',')|first|split(': ')|last }}"
  when: not es_new_install

- name: Asked Elasticsearch version
  set_fact:
    asked_es_version: "{{ elasticsearch_package|split('=')|last }}"

- name: Elasticsearch version change
  set_fact:
    change_es_value: "{{ es_new_install or not asked_es_version == current_es_version }}"

- name: Add required dependencies.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present
- name: Detection Docker
  stat:
    path: /.dockerenv
  register: docker_env

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when:
    - config_system

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true
  when:
    - config_system

- name: Clean des plugins
  when: change_es_value and not es_new_install
  shell: "/usr/share/elasticsearch/bin/elasticsearch-plugin remove analysis-icu"

- name: Install Elasticsearch.
  apt:
    allow_change_held_packages: true
    name: "{{ elasticsearch_package }}"
    state: "{{ elasticsearch_package_state }}"
  notify: restart elasticsearch

- name: Configure Elasticsearch 7+.
  template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
    owner: root
    group: elasticsearch
    mode: 0660
  with_items:
    - /etc/elasticsearch/elasticsearch.yml
    - /etc/elasticsearch/jvm.options.d/heap.options
  notify: restart elasticsearch
  when: elasticsearch_version[0] | int >= 7

- name: Clean des nodes en docker
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "/var/lib/elasticsearch/nodes/0/node.lock"
    - "/var/lib/elasticsearch/nodes/0/snapshot_cache/write.lock"
    - "/etc/elasticsearch/elasticsearch.keystore"
  when: docker_env.stat.exists == True

- name: Regenerate keystore en docker
  shell: /usr/share/elasticsearch/bin/elasticsearch-keystore create
  when: docker_env.stat.exists == True

- name: Generation du fichier systemV en docker
  copy:
    src: "../templates/elasticsearch"
    dest: "/etc/init.d/elasticsearch"
    owner: root
    group: root
    mode: 0750
  when: docker_env.stat.exists == True

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"

- name: Check plugin compatibility
  stat:
    path: "{{ role_path }}/plugins/analysis-icu-{{ asked_es_version }}.zip"
  register: plugin_stat

- name: Check plugin installation
  shell: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
  register: es_plugin_list

- name: Install plugin
  shell: "/usr/share/elasticsearch/bin/elasticsearch-plugin install file://{{ role_path }}/plugins/analysis-icu-{{ asked_es_version }}.zip"
  when:
    - plugin_stat.stat.exists
    - "{{ not 'analysis-icu' in es_version_shell.stdout_lines }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
