---
- name: Collect service facts
  ansible.builtin.service_facts:

- name: Restart elasticsearch with service (no systemd)
  service:
    name: elasticsearch
    state: restarted
  when:
    - 'elasticsearch' in ansible_facts.services
    - ansible_facts.services['elasticsearch'].state == 'running'
